INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 30,'OFF');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 15,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 12,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 30,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 70,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 3);

INSERT INTO BUILDING (ID,BUILDINGID,ROOM_ID) VALUES (1, 1, 1);
INSERT INTO BUILDING (ID,BUILDINGID,ROOM_ID) VALUES (2, 1, 2);
INSERT INTO BUILDING (ID,BUILDINGID,ROOM_ID) VALUES (3, 1, 3);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (4, 40,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (4, 50,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (4, 4, 4);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (5, 25,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (5, 43,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (5, 5, 5);

INSERT INTO BUILDING (ID,BUILDINGID,ROOM_ID) VALUES (4, 2, 4);
INSERT INTO BUILDING (ID,BUILDINGID,ROOM_ID) VALUES (5, 2, 5);