INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 2,'ON');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 20,'ON');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 200,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 3,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 30,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 300,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 3);