INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 2,'ON');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 20,'OFF');
INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 200,'ON');

INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 3,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 30,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 300,'ON');

INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (1, 1, 1);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (2, 2, 2);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (3, 3, 3);

INSERT INTO BUILDING (ID,NOM,BUILDINGID,ROOM_ID) VALUES (1, 'ValentinTower', 1, 1);
INSERT INTO BUILDING (ID,NOM,BUILDINGID,ROOM_ID) VALUES (2, 'ValentinTower', 1, 2);
INSERT INTO BUILDING (ID,NOM,BUILDINGID,ROOM_ID) VALUES (3, 'ValentinTower', 1, 3);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (4, 40,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (4, 50,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (4, 4, 4);

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (5, 25,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (5, 43,'ON');
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID) VALUES (5, 5, 5);

INSERT INTO BUILDING (ID,BUILDINGID,NOM,ROOM_ID) VALUES (4, 2, 'JimmyTower', 4);
INSERT INTO BUILDING (ID,BUILDINGID,NOM,ROOM_ID) VALUES (5, 2, 'JimmyTower', 5);